version: '3'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    volumes:
      - db:/var/lib/mysql
    networks:
      - association-network
    ports:
      - "6666:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  association-backend:
    container_name: association-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - association-network
    depends_on:
      - mysql-db

volumes:
  db:
    driver: local

networks:
  association-network:
    driver: bridge
